#Port used to expose actuator
management:
  server:
    port: 8000
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jackson:
    serialization:
      indent_output: true


#
# Configurations used for application monitoring
#

project:
  name: @project.name@
  version: @project.version@
  java: @java.version@

cloudops:
  server:
    - level:    L1
      type:     dev
      hostname: http://c000xx11.dev.server.com:9999/app/actuator/health
      alias:    L1-DEV-01
    - level:    L1
      type:     dev
      hostname: http://c000xx12.dev.server.com:9999/app/actuator/health
      alias:    L1-DEV-02
    - level:    L2
      type:     test
      hostname: http://c000xx22.test.server.com:9999/app/actuator/health
      alias:    L2-TEST-01

    - level:    LOCALHOST
      type:     dev
      hostname: http://localhost:8000/actuator/health
      alias:    This application
