#Port used to expose actuator
management:
  server:
    port: 8000
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jackson:
    serialization:
      indent_output: true

project:
  name: @project.name@
  version: @project.version@
  java: @java.version@

  env:
    level: L1
    type: dev

cloudops:
  application:
    account:
    - name: console
      instance:
      - level:    LOCALHOST
        type:     dev
        hostname: http://localhost:8080
        actuator: http://localhost:8000
        alias:    DEV-LOCAL_APP01

      - level:    LOCALHOST
        type:     dev
        hostname: http://localhost:9090
        actuator: http://localhost:9000
        alias:    DEV-LOCAL_APP02
